{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2022-24859",
        "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "assignerShortName": "GitHub_M",
        "dateUpdated": "2023-06-10T00:00:00",
        "dateReserved": "2022-02-10T00:00:00",
        "datePublished": "2022-04-18T00:00:00"
    },
    "containers": {
        "cna": {
            "title": "Manipulated inline images can cause Infinite Loop in PyPDF2",
            "providerMetadata": {
                "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
                "shortName": "GitHub_M",
                "dateUpdated": "2023-06-10T00:00:00"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "PyPDF2 is an open source python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. In versions prior to 1.27.5 an attacker who uses this vulnerability can craft a PDF which leads to an infinite loop if the PyPDF2 if the code attempts to get the content stream. The reason is that the last while-loop in `ContentStream._readInlineImage` only terminates when it finds the `EI` token, but never actually checks if the stream has already ended. This issue has been resolved in version `1.27.5`. Users unable to upgrade should validate and PDFs prior to iterating over their content stream."
                }
            ],
            "affected": [
                {
                    "vendor": "py-pdf",
                    "product": "PyPDF2",
                    "versions": [
                        {
                            "version": "< 1.27.5",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://github.com/py-pdf/PyPDF2/security/advisories/GHSA-xcjx-m2pj-8g79"
                },
                {
                    "url": "https://github.com/py-pdf/PyPDF2/issues/329"
                },
                {
                    "url": "https://github.com/py-pdf/PyPDF2/pull/740"
                },
                {
                    "url": "https://github.com/py-pdf/PyPDF2/releases/tag/1.27.5"
                },
                {
                    "name": "[debian-lts-announce] 20220603 [SECURITY] [DLA 3039-1] pypdf2 security update",
                    "tags": [
                        "mailing-list"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2022/06/msg00001.html"
                },
                {
                    "name": "[debian-lts-announce] 20230609 [SECURITY] [DLA 3451-1] pypdf2 security update",
                    "tags": [
                        "mailing-list"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2023/06/msg00013.html"
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "version": "3.1",
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                        "attackVector": "LOCAL",
                        "attackComplexity": "LOW",
                        "privilegesRequired": "NONE",
                        "userInteraction": "NONE",
                        "scope": "UNCHANGED",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "availabilityImpact": "HIGH",
                        "baseScore": 6.2,
                        "baseSeverity": "MEDIUM"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "lang": "en",
                            "description": "CWE-835: Loop with Unreachable Exit Condition ('Infinite Loop')",
                            "cweId": "CWE-835"
                        }
                    ]
                }
            ],
            "source": {
                "advisory": "GHSA-xcjx-m2pj-8g79",
                "discovery": "UNKNOWN"
            }
        }
    }
}