{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2022-41899",
        "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "assignerShortName": "GitHub_M",
        "dateUpdated": "2022-11-18T00:00:00",
        "dateReserved": "2022-09-30T00:00:00",
        "datePublished": "2022-11-18T00:00:00"
    },
    "containers": {
        "cna": {
            "title": "`CHECK` fail via inputs in `SdcaOptimizer` in Tensorflow",
            "providerMetadata": {
                "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
                "shortName": "GitHub_M",
                "dateUpdated": "2022-11-18T00:00:00"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "TensorFlow is an open source platform for machine learning. Inputs `dense_features` or `example_state_data` not of rank 2 will trigger a `CHECK` fail in `SdcaOptimizer`. We have patched the issue in GitHub commit 80ff197d03db2a70c6a111f97dcdacad1b0babfa. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and still in supported range."
                }
            ],
            "affected": [
                {
                    "vendor": "tensorflow",
                    "product": "tensorflow",
                    "versions": [
                        {
                            "version": ">= 2.10.0, < 2.10.1",
                            "status": "affected"
                        },
                        {
                            "version": ">= 2.9.0, < 2.9.3",
                            "status": "affected"
                        },
                        {
                            "version": "< 2.8.4",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-27rc-728f-x5w2"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/80ff197d03db2a70c6a111f97dcdacad1b0babfa"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sdca_internal.cc"
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "version": "3.1",
                        "vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:U/C:N/I:N/A:H",
                        "attackVector": "NETWORK",
                        "attackComplexity": "HIGH",
                        "privilegesRequired": "LOW",
                        "userInteraction": "REQUIRED",
                        "scope": "UNCHANGED",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "availabilityImpact": "HIGH",
                        "baseScore": 4.8,
                        "baseSeverity": "MEDIUM"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "lang": "en",
                            "description": "CWE-20: Improper Input Validation",
                            "cweId": "CWE-20"
                        }
                    ]
                }
            ],
            "source": {
                "advisory": "GHSA-27rc-728f-x5w2",
                "discovery": "UNKNOWN"
            }
        }
    }
}